id: P000628
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD181181
  title: སྔ་འགྱུར་གཡག་ཟེའི་མཁས་གྲུབ་རྣམས་ཀྱི་གསུང་ཐོར་བུ།
  author: ''
  volumes:
    ae23aba17a41444eb56bc4df5dbd751d:
      image_group_id: I1KG16355
      title: ''
      volume_number: 1
      total_pages: 705
