id: I8E151280
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:59:37+00:00'
last_modified: '2022-06-07T12:30:16.201371+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181181
  title: སྔ་འགྱུར་གཡག་ཟེའི་མཁས་གྲུབ་རྣམས་ཀྱི་གསུང་ཐོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8A97:
      image_group_id: I1KG16355
      title: ''
      total_pages: 705
      order: 1
      base_file: 8A97.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
